#!/bin/bash
sudo apt-get install i2c-tools
sudo apt-get install python-pip
sudo apt-get install python-lxml
sudo apt-get install python-webpy
sudo pip install pygal
# user install:
#pip install --user pygal

sudo modprobe i2c-dev
sudo python yawpi.py
