#!/bin/bash

sudo apt-get install i2c-tools
sudo apt-get install python-pip
sudo apt-get install python-lxml
sudo apt-get install python-webpy
sudo pip install pygal
sudo pip install arrow
# user install:
#pip install --user pygal
#pip install --user arrow

# add to crontab/afterstart!
